layout_spectrum: 0.05502253910526633
typography_spectrum: 0.9007406739983708
color:
  brandStrength: 0.11064739339053631
  lightness: 0.11368905496783555
  saturation: 0.6443977553863078
  rhythmicContrast: 0.4536683375481516
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: maxchristensenaudio
